"""add post automation fields

Revision ID: 2383643a4f02
Revises: f3fdadf60351
Create Date: 2026-08-26 15:39:04.925612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2383643a4f02'
down_revision: Union[str, Sequence[str], None] = 'f3fdadf60351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook_posts', sa.Column('automation_status', sa.String(), nullable=True))
    op.add_column('facebook_posts', sa.Column('keyword', sa.String(), nullable=True))
    op.add_column('facebook_posts', sa.Column('reply_message', sa.Text(), nullable=True))
    op.add_column('facebook_posts', sa.Column('dm_message', sa.Text(), nullable=True))
    op.add_column('facebook_posts', sa.Column('is_future_post', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('automation_status', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('keyword', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('reply_message', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('dm_message', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('is_future_post', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_future_post')
    op.drop_column('posts', 'dm_message')
    op.drop_column('posts', 'reply_message')
    op.drop_column('posts', 'keyword')
    op.drop_column('posts', 'automation_status')
    op.drop_column('facebook_posts', 'is_future_post')
    op.drop_column('facebook_posts', 'dm_message')
    op.drop_column('facebook_posts', 'reply_message')
    op.drop_column('facebook_posts', 'keyword')
    op.drop_column('facebook_posts', 'automation_status')
    # ### end Alembic commands ###
