"""add_facebook_models

Revision ID: a80503661ee3
Revises: 
Create Date: 2026-08-05 11:11:42.940639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80503661ee3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_comment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_comment_events_comment_id'), 'facebook_comment_events', ['comment_id'], unique=False)
    op.create_index(op.f('ix_facebook_comment_events_id'), 'facebook_comment_events', ['id'], unique=False)
    op.create_index(op.f('ix_facebook_comment_events_media_id'), 'facebook_comment_events', ['media_id'], unique=False)
    op.create_table('facebook_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('facebook_page_id', sa.String(), nullable=False),
    sa.Column('page_access_token', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_accounts_facebook_page_id'), 'facebook_accounts', ['facebook_page_id'], unique=True)
    op.create_index(op.f('ix_facebook_accounts_id'), 'facebook_accounts', ['id'], unique=False)
    op.create_table('facebook_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('facebook_account_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facebook_account_id'], ['facebook_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_posts_id'), 'facebook_posts', ['id'], unique=False)
    op.create_table('facebook_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['facebook_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_comments_id'), 'facebook_comments', ['id'], unique=False)
    op.add_column('automation_flows', sa.Column('facebook_account_id', sa.Integer(), nullable=True))
    op.alter_column('automation_flows', 'instagram_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'automation_flows', 'facebook_accounts', ['facebook_account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'automation_flows', type_='foreignkey')
    op.alter_column('automation_flows', 'instagram_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('automation_flows', 'facebook_account_id')
    op.drop_index(op.f('ix_facebook_comments_id'), table_name='facebook_comments')
    op.drop_table('facebook_comments')
    op.drop_index(op.f('ix_facebook_posts_id'), table_name='facebook_posts')
    op.drop_table('facebook_posts')
    op.drop_index(op.f('ix_facebook_accounts_id'), table_name='facebook_accounts')
    op.drop_index(op.f('ix_facebook_accounts_facebook_page_id'), table_name='facebook_accounts')
    op.drop_table('facebook_accounts')
    op.drop_index(op.f('ix_facebook_comment_events_media_id'), table_name='facebook_comment_events')
    op.drop_index(op.f('ix_facebook_comment_events_id'), table_name='facebook_comment_events')
    op.drop_index(op.f('ix_facebook_comment_events_comment_id'), table_name='facebook_comment_events')
    op.drop_table('facebook_comment_events')
    # ### end Alembic commands ###
