"""add_dm_automation_models

Revision ID: f3fdadf60351
Revises: a80503661ee3
Create Date: 2026-08-20 17:12:30.892700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3fdadf60351'
down_revision: Union[str, Sequence[str], None] = 'a80503661ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dm_automations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ig_conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ig_conversations_id'), 'ig_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_ig_conversations_participant_id'), 'ig_conversations', ['participant_id'], unique=False)
    op.create_table('ig_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ig_messages_id'), 'ig_messages', ['id'], unique=False)
    op.create_index(op.f('ix_ig_messages_recipient_id'), 'ig_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_ig_messages_sender_id'), 'ig_messages', ['sender_id'], unique=False)
    op.create_table('dm_automation_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('automation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['dm_automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['ig_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dm_automation_executions')
    op.drop_index(op.f('ix_ig_messages_sender_id'), table_name='ig_messages')
    op.drop_index(op.f('ix_ig_messages_recipient_id'), table_name='ig_messages')
    op.drop_index(op.f('ix_ig_messages_id'), table_name='ig_messages')
    op.drop_table('ig_messages')
    op.drop_index(op.f('ix_ig_conversations_participant_id'), table_name='ig_conversations')
    op.drop_index(op.f('ix_ig_conversations_id'), table_name='ig_conversations')
    op.drop_table('ig_conversations')
    op.drop_table('dm_automations')
    # ### end Alembic commands ###
